version: '3.4'

services:
  web:
    build: ./social_media
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./knowme_app/:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./social_media/envs/.env
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres-user
      POTGRES_DB: knowme_db2
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data