version: '3.4'

services:
  web:
    image: kilata151/knowme
    build: ./social_media
    command: gunicorn social_media.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./staticfiles:/tmp/knowme/staticfiles
    ports:
      - 8000:8000
    env_file:
      - .social_media/envs/.env
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres-user
      POTGRES_DB: knowme_db2
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - 81:80
      - 443:443
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web